# Generated by Django 2.2.16 on 2021-05-06 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210506_0433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='national_dex',
        ),
    ]
