# Generated by Django 2.2.16 on 2021-05-06 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_pokemon_national_dex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='national_dex',
        ),
    ]
