# Generated by Django 3.2 on 2021-05-03 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('preevolution_id', models.IntegerField()),
                ('evolution_id', models.IntegerField()),
            ],
        ),
    ]
