# Generated by Django 2.2.16 on 2021-05-03 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20210503_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='national_id',
        ),
    ]
